import { of } from 'rxjs';

import { ForecastWeatherResponse, RealtimeWeatherResponse } from './weather.model';

export const mockRealtimeWeather = of<RealtimeWeatherResponse> ({
  location: {
    name: 'Boston',
    region: 'Lincolnshire',
    country: 'United Kingdom',
    lat: 53.1,
    lon: -0.13,
    tz_id: 'Europe/London',
    localtime_epoch: 1698166994,
    localtime: new Date('2023-10-24 18:03')
  },
  current: {
    last_updated_epoch: 1698166800,
    last_updated: new Date('2023-10-24 18:00'),
    temp_c: 11,
    temp_f: 51.8,
    is_day: 0,
    condition: {
      text: 'Partly cloudy',
      icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
      code: 1003
    },
    wind_mph: 5.6,
    wind_kph: 9,
    wind_degree: 320,
    wind_dir: 'NW',
    pressure_mb: 999,
    pressure_in: 29.5,
    precip_mm: 0,
    precip_in: 0,
    humidity: 94,
    cloud: 50,
    feelslike_c: 10.4,
    feelslike_f: 50.8,
    vis_km: 10,
    vis_miles: 6,
    uv: 1,
    gust_mph: 7.1,
    gust_kph: 11.4
  }
});

export const mockForecastWeather = of<ForecastWeatherResponse> ({
    "location": {
      "name": "Gliwice",
      "region": "",
      "country": "Poland",
      "lat": 50.28,
      "lon": 18.67,
      "tz_id": "Europe/Warsaw",
      "localtime_epoch": 1701514916,
      "localtime": "2023-12-02 12:01"
    },
    "current": {
      "last_updated_epoch": 1701514800,
      "last_updated": "2023-12-02 12:00",
      "temp_c": -3,
      "temp_f": 26.6,
      "is_day": 1,
      "condition": {
        "text": "Patchy heavy snow",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/335.png",
        "code": 1222
      },
      "wind_mph": 11.9,
      "wind_kph": 19.1,
      "wind_degree": 20,
      "wind_dir": "NNE",
      "pressure_mb": 1002,
      "pressure_in": 29.59,
      "precip_mm": 0.77,
      "precip_in": 0.03,
      "humidity": 93,
      "cloud": 75,
      "feelslike_c": -8.8,
      "feelslike_f": 16.3,
      "vis_km": 2.7,
      "vis_miles": 1,
      "uv": 1,
      "gust_mph": 15.1,
      "gust_kph": 24.3
    },
    "forecast": {
      "forecastday": [
        {
          "date": "2023-12-02",
          "date_epoch": 1701475200,
          "day": {
            "maxtemp_c": -1.3,
            "maxtemp_f": 29.7,
            "mintemp_c": -2.2,
            "mintemp_f": 28,
            "avgtemp_c": -1.6,
            "avgtemp_f": 29.1,
            "maxwind_mph": 12.8,
            "maxwind_kph": 20.5,
            "totalprecip_mm": 16.35,
            "totalprecip_in": 0.64,
            "totalsnow_cm": 13.89,
            "avgvis_km": 2.5,
            "avgvis_miles": 1,
            "avghumidity": 96,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 81,
            "daily_will_it_snow": 1,
            "daily_chance_of_snow": 92,
            "condition": {
              "text": "Heavy snow",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/338.png",
              "code": 1225
            },
            "uv": 1
          },
          "astro": {
            "sunrise": "07:24 AM",
            "sunset": "03:45 PM",
            "moonrise": "08:20 PM",
            "moonset": "11:54 AM",
            "moon_phase": "Waning Gibbous",
            "moon_illumination": 79,
            "is_moon_up": 1,
            "is_sun_up": 0
          },
          "hour": [
            {
              "time_epoch": 1701471600,
              "time": "2023-12-02 00:00",
              "temp_c": -1,
              "temp_f": 30.3,
              "is_day": 0,
              "condition": {
                "text": "Moderate snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/332.png",
                "code": 1219
              },
              "wind_mph": 8.5,
              "wind_kph": 13.7,
              "wind_degree": 49,
              "wind_dir": "NE",
              "pressure_mb": 1005,
              "pressure_in": 29.69,
              "precip_mm": 0.17,
              "precip_in": 0.01,
              "humidity": 96,
              "cloud": 100,
              "feelslike_c": -5.3,
              "feelslike_f": 22.4,
              "windchill_c": -5.3,
              "windchill_f": 22.4,
              "heatindex_c": -1,
              "heatindex_f": 30.3,
              "dewpoint_c": -1.5,
              "dewpoint_f": 29.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 96,
              "vis_km": 5,
              "vis_miles": 3,
              "gust_mph": 12.1,
              "gust_kph": 19.4,
              "uv": 1
            },
            {
              "time_epoch": 1701475200,
              "time": "2023-12-02 01:00",
              "temp_c": -1,
              "temp_f": 30.1,
              "is_day": 0,
              "condition": {
                "text": "Moderate snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/332.png",
                "code": 1219
              },
              "wind_mph": 9.6,
              "wind_kph": 15.5,
              "wind_degree": 60,
              "wind_dir": "ENE",
              "pressure_mb": 1004,
              "pressure_in": 29.66,
              "precip_mm": 0.16,
              "precip_in": 0.01,
              "humidity": 96,
              "cloud": 100,
              "feelslike_c": -5.8,
              "feelslike_f": 21.6,
              "windchill_c": -5.8,
              "windchill_f": 21.6,
              "heatindex_c": -1.1,
              "heatindex_f": 30.1,
              "dewpoint_c": -1.6,
              "dewpoint_f": 29.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 96,
              "vis_km": 5,
              "vis_miles": 3,
              "gust_mph": 13.8,
              "gust_kph": 22.1,
              "uv": 1
            },
            {
              "time_epoch": 1701478800,
              "time": "2023-12-02 02:00",
              "temp_c": -1.3,
              "temp_f": 29.7,
              "is_day": 0,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                "code": 1225
              },
              "wind_mph": 9.2,
              "wind_kph": 14.8,
              "wind_degree": 60,
              "wind_dir": "ENE",
              "pressure_mb": 1004,
              "pressure_in": 29.66,
              "precip_mm": 0.25,
              "precip_in": 0.01,
              "humidity": 96,
              "cloud": 100,
              "feelslike_c": -6,
              "feelslike_f": 21.3,
              "windchill_c": -6,
              "windchill_f": 21.3,
              "heatindex_c": -1.3,
              "heatindex_f": 29.7,
              "dewpoint_c": -1.9,
              "dewpoint_f": 28.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 93,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 13.6,
              "gust_kph": 21.9,
              "uv": 1
            },
            {
              "time_epoch": 1701482400,
              "time": "2023-12-02 03:00",
              "temp_c": -1.4,
              "temp_f": 29.6,
              "is_day": 0,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                "code": 1225
              },
              "wind_mph": 10.1,
              "wind_kph": 16.2,
              "wind_degree": 46,
              "wind_dir": "NE",
              "pressure_mb": 1004,
              "pressure_in": 29.66,
              "precip_mm": 0.57,
              "precip_in": 0.02,
              "humidity": 97,
              "cloud": 100,
              "feelslike_c": -6.3,
              "feelslike_f": 20.6,
              "windchill_c": -6.3,
              "windchill_f": 20.6,
              "heatindex_c": -1.4,
              "heatindex_f": 29.6,
              "dewpoint_c": -1.8,
              "dewpoint_f": 28.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 95,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 14.8,
              "gust_kph": 23.9,
              "uv": 1
            },
            {
              "time_epoch": 1701486000,
              "time": "2023-12-02 04:00",
              "temp_c": -1.4,
              "temp_f": 29.5,
              "is_day": 0,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                "code": 1225
              },
              "wind_mph": 10.5,
              "wind_kph": 16.9,
              "wind_degree": 48,
              "wind_dir": "NE",
              "pressure_mb": 1004,
              "pressure_in": 29.65,
              "precip_mm": 0.36,
              "precip_in": 0.01,
              "humidity": 97,
              "cloud": 100,
              "feelslike_c": -6.5,
              "feelslike_f": 20.3,
              "windchill_c": -6.5,
              "windchill_f": 20.3,
              "heatindex_c": -1.4,
              "heatindex_f": 29.5,
              "dewpoint_c": -1.9,
              "dewpoint_f": 28.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 95,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 15.6,
              "gust_kph": 25.1,
              "uv": 1
            },
            {
              "time_epoch": 1701489600,
              "time": "2023-12-02 05:00",
              "temp_c": -1.4,
              "temp_f": 29.5,
              "is_day": 0,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                "code": 1225
              },
              "wind_mph": 11,
              "wind_kph": 17.6,
              "wind_degree": 39,
              "wind_dir": "NE",
              "pressure_mb": 1004,
              "pressure_in": 29.66,
              "precip_mm": 0.59,
              "precip_in": 0.02,
              "humidity": 97,
              "cloud": 100,
              "feelslike_c": -6.6,
              "feelslike_f": 20.1,
              "windchill_c": -6.6,
              "windchill_f": 20.1,
              "heatindex_c": -1.4,
              "heatindex_f": 29.5,
              "dewpoint_c": -1.8,
              "dewpoint_f": 28.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 95,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 16.1,
              "gust_kph": 25.9,
              "uv": 1
            },
            {
              "time_epoch": 1701493200,
              "time": "2023-12-02 06:00",
              "temp_c": -1.6,
              "temp_f": 29.2,
              "is_day": 0,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                "code": 1225
              },
              "wind_mph": 11.2,
              "wind_kph": 18,
              "wind_degree": 42,
              "wind_dir": "NE",
              "pressure_mb": 1004,
              "pressure_in": 29.66,
              "precip_mm": 0.49,
              "precip_in": 0.02,
              "humidity": 96,
              "cloud": 100,
              "feelslike_c": -6.9,
              "feelslike_f": 19.6,
              "windchill_c": -6.9,
              "windchill_f": 19.6,
              "heatindex_c": -1.6,
              "heatindex_f": 29.2,
              "dewpoint_c": -2.1,
              "dewpoint_f": 28.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 94,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 16.4,
              "gust_kph": 26.3,
              "uv": 1
            },
            {
              "time_epoch": 1701496800,
              "time": "2023-12-02 07:00",
              "temp_c": -1.8,
              "temp_f": 28.7,
              "is_day": 0,
              "condition": {
                "text": "Moderate snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/332.png",
                "code": 1219
              },
              "wind_mph": 11.2,
              "wind_kph": 18,
              "wind_degree": 43,
              "wind_dir": "NE",
              "pressure_mb": 1004,
              "pressure_in": 29.66,
              "precip_mm": 0.18,
              "precip_in": 0.01,
              "humidity": 95,
              "cloud": 97,
              "feelslike_c": -7.2,
              "feelslike_f": 19,
              "windchill_c": -7.2,
              "windchill_f": 19,
              "heatindex_c": -1.8,
              "heatindex_f": 28.7,
              "dewpoint_c": -2.5,
              "dewpoint_f": 27.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 94,
              "vis_km": 5,
              "vis_miles": 3,
              "gust_mph": 16.4,
              "gust_kph": 26.3,
              "uv": 1
            },
            {
              "time_epoch": 1701500400,
              "time": "2023-12-02 08:00",
              "temp_c": -1.8,
              "temp_f": 28.7,
              "is_day": 1,
              "condition": {
                "text": "Moderate snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/332.png",
                "code": 1219
              },
              "wind_mph": 10.7,
              "wind_kph": 17.3,
              "wind_degree": 48,
              "wind_dir": "NE",
              "pressure_mb": 1004,
              "pressure_in": 29.66,
              "precip_mm": 0.19,
              "precip_in": 0.01,
              "humidity": 95,
              "cloud": 100,
              "feelslike_c": -7.1,
              "feelslike_f": 19.2,
              "windchill_c": -7.1,
              "windchill_f": 19.2,
              "heatindex_c": -1.9,
              "heatindex_f": 28.7,
              "dewpoint_c": -2.6,
              "dewpoint_f": 27.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 93,
              "vis_km": 5,
              "vis_miles": 3,
              "gust_mph": 15.4,
              "gust_kph": 24.8,
              "uv": 1
            },
            {
              "time_epoch": 1701504000,
              "time": "2023-12-02 09:00",
              "temp_c": -1.6,
              "temp_f": 29.2,
              "is_day": 1,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/338.png",
                "code": 1225
              },
              "wind_mph": 10.7,
              "wind_kph": 17.3,
              "wind_degree": 40,
              "wind_dir": "NE",
              "pressure_mb": 1005,
              "pressure_in": 29.67,
              "precip_mm": 0.45,
              "precip_in": 0.02,
              "humidity": 96,
              "cloud": 100,
              "feelslike_c": -6.8,
              "feelslike_f": 19.9,
              "windchill_c": -6.8,
              "windchill_f": 19.9,
              "heatindex_c": -1.6,
              "heatindex_f": 29.2,
              "dewpoint_c": -2.1,
              "dewpoint_f": 28.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 93,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 14.7,
              "gust_kph": 23.7,
              "uv": 1
            },
            {
              "time_epoch": 1701507600,
              "time": "2023-12-02 10:00",
              "temp_c": -1.3,
              "temp_f": 29.7,
              "is_day": 1,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/338.png",
                "code": 1225
              },
              "wind_mph": 11,
              "wind_kph": 17.6,
              "wind_degree": 36,
              "wind_dir": "NE",
              "pressure_mb": 1005,
              "pressure_in": 29.67,
              "precip_mm": 0.6,
              "precip_in": 0.02,
              "humidity": 96,
              "cloud": 100,
              "feelslike_c": -6.5,
              "feelslike_f": 20.3,
              "windchill_c": -6.5,
              "windchill_f": 20.3,
              "heatindex_c": -1.3,
              "heatindex_f": 29.7,
              "dewpoint_c": -1.8,
              "dewpoint_f": 28.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 93,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 14.5,
              "gust_kph": 23.3,
              "uv": 1
            },
            {
              "time_epoch": 1701511200,
              "time": "2023-12-02 11:00",
              "temp_c": -1.4,
              "temp_f": 29.5,
              "is_day": 1,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/338.png",
                "code": 1225
              },
              "wind_mph": 11.4,
              "wind_kph": 18.4,
              "wind_degree": 34,
              "wind_dir": "NE",
              "pressure_mb": 1005,
              "pressure_in": 29.66,
              "precip_mm": 0.74,
              "precip_in": 0.03,
              "humidity": 96,
              "cloud": 100,
              "feelslike_c": -6.7,
              "feelslike_f": 19.9,
              "windchill_c": -6.7,
              "windchill_f": 19.9,
              "heatindex_c": -1.4,
              "heatindex_f": 29.5,
              "dewpoint_c": -1.9,
              "dewpoint_f": 28.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 92,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 15.1,
              "gust_kph": 24.3,
              "uv": 1
            },
            {
              "time_epoch": 1701514800,
              "time": "2023-12-02 12:00",
              "temp_c": -3,
              "temp_f": 26.6,
              "is_day": 1,
              "condition": {
                "text": "Patchy heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/335.png",
                "code": 1222
              },
              "wind_mph": 11.9,
              "wind_kph": 19.1,
              "wind_degree": 20,
              "wind_dir": "NNE",
              "pressure_mb": 1002,
              "pressure_in": 29.59,
              "precip_mm": 0.77,
              "precip_in": 0.03,
              "humidity": 93,
              "cloud": 75,
              "feelslike_c": -6.7,
              "feelslike_f": 20,
              "windchill_c": -6.7,
              "windchill_f": 20,
              "heatindex_c": -1.3,
              "heatindex_f": 29.6,
              "dewpoint_c": -1.9,
              "dewpoint_f": 28.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 92,
              "vis_km": 2.7,
              "vis_miles": 1,
              "gust_mph": 15.1,
              "gust_kph": 24.3,
              "uv": 1
            },
            {
              "time_epoch": 1701518400,
              "time": "2023-12-02 13:00",
              "temp_c": -1.3,
              "temp_f": 29.6,
              "is_day": 1,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/338.png",
                "code": 1225
              },
              "wind_mph": 11.6,
              "wind_kph": 18.7,
              "wind_degree": 28,
              "wind_dir": "NNE",
              "pressure_mb": 1004,
              "pressure_in": 29.66,
              "precip_mm": 0.9,
              "precip_in": 0.04,
              "humidity": 96,
              "cloud": 100,
              "feelslike_c": -6.7,
              "feelslike_f": 20,
              "windchill_c": -6.7,
              "windchill_f": 20,
              "heatindex_c": -1.3,
              "heatindex_f": 29.6,
              "dewpoint_c": -1.8,
              "dewpoint_f": 28.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 92,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 15.6,
              "gust_kph": 25.1,
              "uv": 1
            },
            {
              "time_epoch": 1701522000,
              "time": "2023-12-02 14:00",
              "temp_c": -1.3,
              "temp_f": 29.6,
              "is_day": 1,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/338.png",
                "code": 1225
              },
              "wind_mph": 10.7,
              "wind_kph": 17.3,
              "wind_degree": 25,
              "wind_dir": "NNE",
              "pressure_mb": 1005,
              "pressure_in": 29.68,
              "precip_mm": 1.73,
              "precip_in": 0.07,
              "humidity": 97,
              "cloud": 100,
              "feelslike_c": -6.5,
              "feelslike_f": 20.3,
              "windchill_c": -6.5,
              "windchill_f": 20.3,
              "heatindex_c": -1.4,
              "heatindex_f": 29.6,
              "dewpoint_c": -1.8,
              "dewpoint_f": 28.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 91,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 14.7,
              "gust_kph": 23.7,
              "uv": 1
            },
            {
              "time_epoch": 1701525600,
              "time": "2023-12-02 15:00",
              "temp_c": -1.6,
              "temp_f": 29.1,
              "is_day": 1,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/338.png",
                "code": 1225
              },
              "wind_mph": 12.3,
              "wind_kph": 19.8,
              "wind_degree": 22,
              "wind_dir": "NNE",
              "pressure_mb": 1005,
              "pressure_in": 29.67,
              "precip_mm": 0.64,
              "precip_in": 0.03,
              "humidity": 96,
              "cloud": 100,
              "feelslike_c": -7.2,
              "feelslike_f": 19,
              "windchill_c": -7.2,
              "windchill_f": 19,
              "heatindex_c": -1.6,
              "heatindex_f": 29.1,
              "dewpoint_c": -2.1,
              "dewpoint_f": 28.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 91,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 17.2,
              "gust_kph": 27.6,
              "uv": 1
            },
            {
              "time_epoch": 1701529200,
              "time": "2023-12-02 16:00",
              "temp_c": -1.9,
              "temp_f": 28.6,
              "is_day": 0,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                "code": 1225
              },
              "wind_mph": 11.4,
              "wind_kph": 18.4,
              "wind_degree": 20,
              "wind_dir": "NNE",
              "pressure_mb": 1005,
              "pressure_in": 29.69,
              "precip_mm": 0.69,
              "precip_in": 0.03,
              "humidity": 96,
              "cloud": 100,
              "feelslike_c": -7.3,
              "feelslike_f": 18.8,
              "windchill_c": -7.3,
              "windchill_f": 18.8,
              "heatindex_c": -1.9,
              "heatindex_f": 28.6,
              "dewpoint_c": -2.4,
              "dewpoint_f": 27.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 91,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 16.2,
              "gust_kph": 26.1,
              "uv": 1
            },
            {
              "time_epoch": 1701532800,
              "time": "2023-12-02 17:00",
              "temp_c": -2.1,
              "temp_f": 28.3,
              "is_day": 0,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                "code": 1225
              },
              "wind_mph": 11,
              "wind_kph": 17.6,
              "wind_degree": 7,
              "wind_dir": "N",
              "pressure_mb": 1007,
              "pressure_in": 29.72,
              "precip_mm": 1.79,
              "precip_in": 0.07,
              "humidity": 97,
              "cloud": 100,
              "feelslike_c": -7.5,
              "feelslike_f": 18.6,
              "windchill_c": -7.5,
              "windchill_f": 18.6,
              "heatindex_c": -2.1,
              "heatindex_f": 28.3,
              "dewpoint_c": -2.5,
              "dewpoint_f": 27.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 90,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 15.7,
              "gust_kph": 25.2,
              "uv": 1
            },
            {
              "time_epoch": 1701536400,
              "time": "2023-12-02 18:00",
              "temp_c": -2.1,
              "temp_f": 28.2,
              "is_day": 0,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                "code": 1225
              },
              "wind_mph": 11.4,
              "wind_kph": 18.4,
              "wind_degree": 8,
              "wind_dir": "N",
              "pressure_mb": 1006,
              "pressure_in": 29.72,
              "precip_mm": 0.81,
              "precip_in": 0.03,
              "humidity": 96,
              "cloud": 100,
              "feelslike_c": -7.7,
              "feelslike_f": 18.2,
              "windchill_c": -7.7,
              "windchill_f": 18.2,
              "heatindex_c": -2.1,
              "heatindex_f": 28.2,
              "dewpoint_c": -2.7,
              "dewpoint_f": 27.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 90,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 16.2,
              "gust_kph": 26.1,
              "uv": 1
            },
            {
              "time_epoch": 1701540000,
              "time": "2023-12-02 19:00",
              "temp_c": -2.2,
              "temp_f": 28,
              "is_day": 0,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                "code": 1225
              },
              "wind_mph": 12.8,
              "wind_kph": 20.5,
              "wind_degree": 355,
              "wind_dir": "N",
              "pressure_mb": 1006,
              "pressure_in": 29.72,
              "precip_mm": 0.81,
              "precip_in": 0.03,
              "humidity": 97,
              "cloud": 97,
              "feelslike_c": -8.1,
              "feelslike_f": 17.3,
              "windchill_c": -8.1,
              "windchill_f": 17.3,
              "heatindex_c": -2.2,
              "heatindex_f": 28,
              "dewpoint_c": -2.7,
              "dewpoint_f": 27.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 90,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 18.3,
              "gust_kph": 29.4,
              "uv": 1
            },
            {
              "time_epoch": 1701543600,
              "time": "2023-12-02 20:00",
              "temp_c": -2.1,
              "temp_f": 28.1,
              "is_day": 0,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                "code": 1225
              },
              "wind_mph": 10.7,
              "wind_kph": 17.3,
              "wind_degree": 342,
              "wind_dir": "NNW",
              "pressure_mb": 1008,
              "pressure_in": 29.77,
              "precip_mm": 0.99,
              "precip_in": 0.04,
              "humidity": 97,
              "cloud": 93,
              "feelslike_c": -7.5,
              "feelslike_f": 18.5,
              "windchill_c": -7.5,
              "windchill_f": 18.5,
              "heatindex_c": -2.1,
              "heatindex_f": 28.1,
              "dewpoint_c": -2.6,
              "dewpoint_f": 27.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 89,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 15.5,
              "gust_kph": 24.9,
              "uv": 1
            },
            {
              "time_epoch": 1701547200,
              "time": "2023-12-02 21:00",
              "temp_c": -2.1,
              "temp_f": 28.3,
              "is_day": 0,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                "code": 1225
              },
              "wind_mph": 9.6,
              "wind_kph": 15.5,
              "wind_degree": 324,
              "wind_dir": "NW",
              "pressure_mb": 1009,
              "pressure_in": 29.8,
              "precip_mm": 0.98,
              "precip_in": 0.04,
              "humidity": 97,
              "cloud": 100,
              "feelslike_c": -7,
              "feelslike_f": 19.3,
              "windchill_c": -7,
              "windchill_f": 19.3,
              "heatindex_c": -2.1,
              "heatindex_f": 28.3,
              "dewpoint_c": -2.4,
              "dewpoint_f": 27.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 89,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 13.8,
              "gust_kph": 22.3,
              "uv": 1
            },
            {
              "time_epoch": 1701550800,
              "time": "2023-12-02 22:00",
              "temp_c": -2,
              "temp_f": 28.4,
              "is_day": 0,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                "code": 1225
              },
              "wind_mph": 9.2,
              "wind_kph": 14.8,
              "wind_degree": 313,
              "wind_dir": "NW",
              "pressure_mb": 1010,
              "pressure_in": 29.84,
              "precip_mm": 0.8,
              "precip_in": 0.03,
              "humidity": 97,
              "cloud": 100,
              "feelslike_c": -6.8,
              "feelslike_f": 19.7,
              "windchill_c": -6.8,
              "windchill_f": 19.7,
              "heatindex_c": -2,
              "heatindex_f": 28.4,
              "dewpoint_c": -2.4,
              "dewpoint_f": 27.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 89,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 13.2,
              "gust_kph": 21.3,
              "uv": 1
            },
            {
              "time_epoch": 1701554400,
              "time": "2023-12-02 23:00",
              "temp_c": -2,
              "temp_f": 28.4,
              "is_day": 0,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                "code": 1225
              },
              "wind_mph": 10.3,
              "wind_kph": 16.6,
              "wind_degree": 311,
              "wind_dir": "NW",
              "pressure_mb": 1011,
              "pressure_in": 29.86,
              "precip_mm": 0.69,
              "precip_in": 0.03,
              "humidity": 97,
              "cloud": 100,
              "feelslike_c": -7.2,
              "feelslike_f": 19,
              "windchill_c": -7.2,
              "windchill_f": 19,
              "heatindex_c": -2,
              "heatindex_f": 28.4,
              "dewpoint_c": -2.4,
              "dewpoint_f": 27.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 88,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 14.8,
              "gust_kph": 23.8,
              "uv": 1
            }
          ]
        },
        {
          "date": "2023-12-03",
          "date_epoch": 1701561600,
          "day": {
            "maxtemp_c": -2.6,
            "maxtemp_f": 27.4,
            "mintemp_c": -10.6,
            "mintemp_f": 12.9,
            "avgtemp_c": -5.2,
            "avgtemp_f": 22.6,
            "maxwind_mph": 13,
            "maxwind_kph": 20.9,
            "totalprecip_mm": 2.09,
            "totalprecip_in": 0.08,
            "totalsnow_cm": 1.72,
            "avgvis_km": 6.1,
            "avgvis_miles": 3,
            "avghumidity": 94,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 80,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 66,
            "condition": {
              "text": "Light freezing rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/311.png",
              "code": 1198
            },
            "uv": 1
          },
          "astro": {
            "sunrise": "07:26 AM",
            "sunset": "03:45 PM",
            "moonrise": "09:32 PM",
            "moonset": "12:14 PM",
            "moon_phase": "Waning Gibbous",
            "moon_illumination": 71,
            "is_moon_up": 1,
            "is_sun_up": 0
          },
          "hour": [
            {
              "time_epoch": 1701558000,
              "time": "2023-12-03 00:00",
              "temp_c": -2.1,
              "temp_f": 28.2,
              "is_day": 0,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                "code": 1225
              },
              "wind_mph": 10.5,
              "wind_kph": 16.9,
              "wind_degree": 305,
              "wind_dir": "NW",
              "pressure_mb": 1012,
              "pressure_in": 29.89,
              "precip_mm": 0.42,
              "precip_in": 0.02,
              "humidity": 97,
              "cloud": 100,
              "feelslike_c": -7.4,
              "feelslike_f": 18.8,
              "windchill_c": -7.4,
              "windchill_f": 18.8,
              "heatindex_c": -2.1,
              "heatindex_f": 28.2,
              "dewpoint_c": -2.5,
              "dewpoint_f": 27.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 88,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 15.1,
              "gust_kph": 24.3,
              "uv": 1
            },
            {
              "time_epoch": 1701561600,
              "time": "2023-12-03 01:00",
              "temp_c": -2.6,
              "temp_f": 27.2,
              "is_day": 0,
              "condition": {
                "text": "Moderate snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/332.png",
                "code": 1219
              },
              "wind_mph": 11.9,
              "wind_kph": 19.1,
              "wind_degree": 299,
              "wind_dir": "WNW",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 0.2,
              "precip_in": 0.01,
              "humidity": 96,
              "cloud": 100,
              "feelslike_c": -8.4,
              "feelslike_f": 16.8,
              "windchill_c": -8.4,
              "windchill_f": 16.8,
              "heatindex_c": -2.6,
              "heatindex_f": 27.2,
              "dewpoint_c": -3.2,
              "dewpoint_f": 26.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 88,
              "vis_km": 5,
              "vis_miles": 3,
              "gust_mph": 16.8,
              "gust_kph": 27,
              "uv": 1
            },
            {
              "time_epoch": 1701565200,
              "time": "2023-12-03 02:00",
              "temp_c": -3.7,
              "temp_f": 25.4,
              "is_day": 0,
              "condition": {
                "text": "Moderate snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/332.png",
                "code": 1219
              },
              "wind_mph": 12.8,
              "wind_kph": 20.5,
              "wind_degree": 301,
              "wind_dir": "WNW",
              "pressure_mb": 1014,
              "pressure_in": 29.94,
              "precip_mm": 0.08,
              "precip_in": 0,
              "humidity": 95,
              "cloud": 100,
              "feelslike_c": -10,
              "feelslike_f": 14.1,
              "windchill_c": -10,
              "windchill_f": 14.1,
              "heatindex_c": -3.7,
              "heatindex_f": 25.4,
              "dewpoint_c": -4.4,
              "dewpoint_f": 24.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 53,
              "vis_km": 5,
              "vis_miles": 3,
              "gust_mph": 18.2,
              "gust_kph": 29.3,
              "uv": 1
            },
            {
              "time_epoch": 1701568800,
              "time": "2023-12-03 03:00",
              "temp_c": -4.3,
              "temp_f": 24.2,
              "is_day": 0,
              "condition": {
                "text": "Moderate snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/332.png",
                "code": 1219
              },
              "wind_mph": 12.8,
              "wind_kph": 20.5,
              "wind_degree": 299,
              "wind_dir": "WNW",
              "pressure_mb": 1015,
              "pressure_in": 29.97,
              "precip_mm": 0.16,
              "precip_in": 0.01,
              "humidity": 95,
              "cloud": 100,
              "feelslike_c": -10.8,
              "feelslike_f": 12.6,
              "windchill_c": -10.8,
              "windchill_f": 12.6,
              "heatindex_c": -4.3,
              "heatindex_f": 24.2,
              "dewpoint_c": -5,
              "dewpoint_f": 23,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 87,
              "vis_km": 5,
              "vis_miles": 3,
              "gust_mph": 18.6,
              "gust_kph": 30,
              "uv": 1
            },
            {
              "time_epoch": 1701572400,
              "time": "2023-12-03 04:00",
              "temp_c": -4.5,
              "temp_f": 24,
              "is_day": 0,
              "condition": {
                "text": "Moderate snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/332.png",
                "code": 1219
              },
              "wind_mph": 13,
              "wind_kph": 20.9,
              "wind_degree": 296,
              "wind_dir": "WNW",
              "pressure_mb": 1016,
              "pressure_in": 30,
              "precip_mm": 0.1,
              "precip_in": 0,
              "humidity": 94,
              "cloud": 100,
              "feelslike_c": -11,
              "feelslike_f": 12.1,
              "windchill_c": -11,
              "windchill_f": 12.1,
              "heatindex_c": -4.5,
              "heatindex_f": 24,
              "dewpoint_c": -5.2,
              "dewpoint_f": 22.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 53,
              "vis_km": 5,
              "vis_miles": 3,
              "gust_mph": 18.8,
              "gust_kph": 30.3,
              "uv": 1
            },
            {
              "time_epoch": 1701576000,
              "time": "2023-12-03 05:00",
              "temp_c": -4.7,
              "temp_f": 23.6,
              "is_day": 0,
              "condition": {
                "text": "Moderate snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/332.png",
                "code": 1219
              },
              "wind_mph": 13,
              "wind_kph": 20.9,
              "wind_degree": 297,
              "wind_dir": "WNW",
              "pressure_mb": 1017,
              "pressure_in": 30.02,
              "precip_mm": 0.18,
              "precip_in": 0.01,
              "humidity": 95,
              "cloud": 100,
              "feelslike_c": -11.3,
              "feelslike_f": 11.7,
              "windchill_c": -11.3,
              "windchill_f": 11.7,
              "heatindex_c": -4.7,
              "heatindex_f": 23.6,
              "dewpoint_c": -5.4,
              "dewpoint_f": 22.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 86,
              "vis_km": 5,
              "vis_miles": 3,
              "gust_mph": 18.8,
              "gust_kph": 30.3,
              "uv": 1
            },
            {
              "time_epoch": 1701579600,
              "time": "2023-12-03 06:00",
              "temp_c": -4.6,
              "temp_f": 23.8,
              "is_day": 0,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                "code": 1225
              },
              "wind_mph": 12.5,
              "wind_kph": 20.2,
              "wind_degree": 295,
              "wind_dir": "WNW",
              "pressure_mb": 1017,
              "pressure_in": 30.04,
              "precip_mm": 0.27,
              "precip_in": 0.01,
              "humidity": 95,
              "cloud": 100,
              "feelslike_c": -11,
              "feelslike_f": 12.2,
              "windchill_c": -11,
              "windchill_f": 12.2,
              "heatindex_c": -4.6,
              "heatindex_f": 23.8,
              "dewpoint_c": -5.2,
              "dewpoint_f": 22.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 86,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 18.1,
              "gust_kph": 29.1,
              "uv": 1
            },
            {
              "time_epoch": 1701583200,
              "time": "2023-12-03 07:00",
              "temp_c": -4.5,
              "temp_f": 24,
              "is_day": 0,
              "condition": {
                "text": "Heavy snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                "code": 1225
              },
              "wind_mph": 11.9,
              "wind_kph": 19.1,
              "wind_degree": 294,
              "wind_dir": "WNW",
              "pressure_mb": 1018,
              "pressure_in": 30.07,
              "precip_mm": 0.31,
              "precip_in": 0.01,
              "humidity": 95,
              "cloud": 100,
              "feelslike_c": -10.7,
              "feelslike_f": 12.7,
              "windchill_c": -10.7,
              "windchill_f": 12.7,
              "heatindex_c": -4.5,
              "heatindex_f": 24,
              "dewpoint_c": -5.1,
              "dewpoint_f": 22.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 85,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 17.1,
              "gust_kph": 27.5,
              "uv": 1
            },
            {
              "time_epoch": 1701586800,
              "time": "2023-12-03 08:00",
              "temp_c": -4.2,
              "temp_f": 24.4,
              "is_day": 1,
              "condition": {
                "text": "Moderate snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/332.png",
                "code": 1219
              },
              "wind_mph": 11.2,
              "wind_kph": 18,
              "wind_degree": 293,
              "wind_dir": "WNW",
              "pressure_mb": 1020,
              "pressure_in": 30.11,
              "precip_mm": 0.09,
              "precip_in": 0,
              "humidity": 95,
              "cloud": 100,
              "feelslike_c": -10.2,
              "feelslike_f": 13.6,
              "windchill_c": -10.2,
              "windchill_f": 13.6,
              "heatindex_c": -4.2,
              "heatindex_f": 24.4,
              "dewpoint_c": -5,
              "dewpoint_f": 23,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 80,
              "vis_km": 5,
              "vis_miles": 3,
              "gust_mph": 15.8,
              "gust_kph": 25.4,
              "uv": 1
            },
            {
              "time_epoch": 1701590400,
              "time": "2023-12-03 09:00",
              "temp_c": -4.1,
              "temp_f": 24.6,
              "is_day": 1,
              "condition": {
                "text": "Light snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/326.png",
                "code": 1213
              },
              "wind_mph": 11.2,
              "wind_kph": 18,
              "wind_degree": 293,
              "wind_dir": "WNW",
              "pressure_mb": 1020,
              "pressure_in": 30.13,
              "precip_mm": 0.04,
              "precip_in": 0,
              "humidity": 94,
              "cloud": 100,
              "feelslike_c": -10.1,
              "feelslike_f": 13.9,
              "windchill_c": -10.1,
              "windchill_f": 13.9,
              "heatindex_c": -4.1,
              "heatindex_f": 24.6,
              "dewpoint_c": -4.9,
              "dewpoint_f": 23.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 73,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.5,
              "gust_kph": 24.9,
              "uv": 1
            },
            {
              "time_epoch": 1701594000,
              "time": "2023-12-03 10:00",
              "temp_c": -3.6,
              "temp_f": 25.5,
              "is_day": 1,
              "condition": {
                "text": "Light snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/326.png",
                "code": 1213
              },
              "wind_mph": 11.2,
              "wind_kph": 18,
              "wind_degree": 295,
              "wind_dir": "WNW",
              "pressure_mb": 1021,
              "pressure_in": 30.15,
              "precip_mm": 0.04,
              "precip_in": 0,
              "humidity": 93,
              "cloud": 100,
              "feelslike_c": -9.4,
              "feelslike_f": 15,
              "windchill_c": -9.4,
              "windchill_f": 15,
              "heatindex_c": -3.6,
              "heatindex_f": 25.5,
              "dewpoint_c": -4.6,
              "dewpoint_f": 23.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 84,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.9,
              "gust_kph": 24,
              "uv": 1
            },
            {
              "time_epoch": 1701597600,
              "time": "2023-12-03 11:00",
              "temp_c": -3.2,
              "temp_f": 26.2,
              "is_day": 1,
              "condition": {
                "text": "Light snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/326.png",
                "code": 1213
              },
              "wind_mph": 11,
              "wind_kph": 17.6,
              "wind_degree": 296,
              "wind_dir": "WNW",
              "pressure_mb": 1021,
              "pressure_in": 30.16,
              "precip_mm": 0.02,
              "precip_in": 0,
              "humidity": 90,
              "cloud": 100,
              "feelslike_c": -8.9,
              "feelslike_f": 16,
              "windchill_c": -8.9,
              "windchill_f": 16,
              "heatindex_c": -3.2,
              "heatindex_f": 26.2,
              "dewpoint_c": -4.6,
              "dewpoint_f": 23.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 61,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.5,
              "gust_kph": 23.3,
              "uv": 1
            },
            {
              "time_epoch": 1701601200,
              "time": "2023-12-03 12:00",
              "temp_c": -2.9,
              "temp_f": 26.7,
              "is_day": 1,
              "condition": {
                "text": "Light freezing rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/311.png",
                "code": 1198
              },
              "wind_mph": 10.5,
              "wind_kph": 16.9,
              "wind_degree": 293,
              "wind_dir": "WNW",
              "pressure_mb": 1022,
              "pressure_in": 30.17,
              "precip_mm": 0.01,
              "precip_in": 0,
              "humidity": 87,
              "cloud": 100,
              "feelslike_c": -8.4,
              "feelslike_f": 16.9,
              "windchill_c": -8.4,
              "windchill_f": 16.9,
              "heatindex_c": -2.9,
              "heatindex_f": 26.7,
              "dewpoint_c": -4.8,
              "dewpoint_f": 23.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 81,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.9,
              "gust_kph": 22.4,
              "uv": 1
            },
            {
              "time_epoch": 1701604800,
              "time": "2023-12-03 13:00",
              "temp_c": -2.7,
              "temp_f": 27.1,
              "is_day": 1,
              "condition": {
                "text": "Light freezing rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/311.png",
                "code": 1198
              },
              "wind_mph": 9.6,
              "wind_kph": 15.5,
              "wind_degree": 289,
              "wind_dir": "WNW",
              "pressure_mb": 1022,
              "pressure_in": 30.18,
              "precip_mm": 0.01,
              "precip_in": 0,
              "humidity": 85,
              "cloud": 100,
              "feelslike_c": -7.9,
              "feelslike_f": 17.9,
              "windchill_c": -7.9,
              "windchill_f": 17.9,
              "heatindex_c": -2.7,
              "heatindex_f": 27.1,
              "dewpoint_c": -4.9,
              "dewpoint_f": 23.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 83,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.9,
              "gust_kph": 20.8,
              "uv": 1
            },
            {
              "time_epoch": 1701608400,
              "time": "2023-12-03 14:00",
              "temp_c": -2.6,
              "temp_f": 27.4,
              "is_day": 1,
              "condition": {
                "text": "Light freezing rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/311.png",
                "code": 1198
              },
              "wind_mph": 7.8,
              "wind_kph": 12.6,
              "wind_degree": 278,
              "wind_dir": "W",
              "pressure_mb": 1022,
              "pressure_in": 30.18,
              "precip_mm": 0.01,
              "precip_in": 0,
              "humidity": 86,
              "cloud": 93,
              "feelslike_c": -7,
              "feelslike_f": 19.3,
              "windchill_c": -7,
              "windchill_f": 19.3,
              "heatindex_c": -2.6,
              "heatindex_f": 27.4,
              "dewpoint_c": -4.6,
              "dewpoint_f": 23.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 87,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.7,
              "gust_kph": 17.2,
              "uv": 1
            },
            {
              "time_epoch": 1701612000,
              "time": "2023-12-03 15:00",
              "temp_c": -3.4,
              "temp_f": 25.9,
              "is_day": 1,
              "condition": {
                "text": "Light freezing rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/311.png",
                "code": 1198
              },
              "wind_mph": 5.6,
              "wind_kph": 9,
              "wind_degree": 248,
              "wind_dir": "WSW",
              "pressure_mb": 1022,
              "pressure_in": 30.19,
              "precip_mm": 0.01,
              "precip_in": 0,
              "humidity": 91,
              "cloud": 88,
              "feelslike_c": -7,
              "feelslike_f": 19.4,
              "windchill_c": -7,
              "windchill_f": 19.4,
              "heatindex_c": -3.4,
              "heatindex_f": 26,
              "dewpoint_c": -4.6,
              "dewpoint_f": 23.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 86,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 8.5,
              "gust_kph": 13.6,
              "uv": 1
            },
            {
              "time_epoch": 1701615600,
              "time": "2023-12-03 16:00",
              "temp_c": -6.5,
              "temp_f": 20.2,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 5.1,
              "wind_kph": 8.3,
              "wind_degree": 217,
              "wind_dir": "SW",
              "pressure_mb": 1023,
              "pressure_in": 30.22,
              "precip_mm": 0.01,
              "precip_in": 0,
              "humidity": 96,
              "cloud": 62,
              "feelslike_c": -10.5,
              "feelslike_f": 13.1,
              "windchill_c": -10.5,
              "windchill_f": 13.1,
              "heatindex_c": -6.5,
              "heatindex_f": 20.2,
              "dewpoint_c": -7.1,
              "dewpoint_f": 19.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 66,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 10.8,
              "gust_kph": 17.4,
              "uv": 1
            },
            {
              "time_epoch": 1701619200,
              "time": "2023-12-03 17:00",
              "temp_c": -7.8,
              "temp_f": 17.9,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 5.8,
              "wind_kph": 9.4,
              "wind_degree": 210,
              "wind_dir": "SSW",
              "pressure_mb": 1024,
              "pressure_in": 30.23,
              "precip_mm": 0.01,
              "precip_in": 0,
              "humidity": 95,
              "cloud": 99,
              "feelslike_c": -12.5,
              "feelslike_f": 9.6,
              "windchill_c": -12.5,
              "windchill_f": 9.6,
              "heatindex_c": -7.8,
              "heatindex_f": 17.9,
              "dewpoint_c": -8.5,
              "dewpoint_f": 16.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 84,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 12.2,
              "gust_kph": 19.7,
              "uv": 1
            },
            {
              "time_epoch": 1701622800,
              "time": "2023-12-03 18:00",
              "temp_c": -6.6,
              "temp_f": 20.1,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 7.2,
              "wind_kph": 11.5,
              "wind_degree": 215,
              "wind_dir": "SW",
              "pressure_mb": 1024,
              "pressure_in": 30.24,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 92,
              "cloud": 95,
              "feelslike_c": -11.7,
              "feelslike_f": 11,
              "windchill_c": -11.7,
              "windchill_f": 11,
              "heatindex_c": -6.6,
              "heatindex_f": 20.1,
              "dewpoint_c": -7.7,
              "dewpoint_f": 18.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.9,
              "gust_kph": 20.8,
              "uv": 1
            },
            {
              "time_epoch": 1701626400,
              "time": "2023-12-03 19:00",
              "temp_c": -7.3,
              "temp_f": 18.9,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 6,
              "wind_kph": 9.7,
              "wind_degree": 225,
              "wind_dir": "SW",
              "pressure_mb": 1025,
              "pressure_in": 30.26,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 94,
              "cloud": 79,
              "feelslike_c": -11.9,
              "feelslike_f": 10.5,
              "windchill_c": -11.9,
              "windchill_f": 10.5,
              "heatindex_c": -7.3,
              "heatindex_f": 18.9,
              "dewpoint_c": -8.1,
              "dewpoint_f": 17.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 11.3,
              "gust_kph": 18.3,
              "uv": 1
            },
            {
              "time_epoch": 1701630000,
              "time": "2023-12-03 20:00",
              "temp_c": -9.3,
              "temp_f": 15.2,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 5.4,
              "wind_kph": 8.6,
              "wind_degree": 222,
              "wind_dir": "SW",
              "pressure_mb": 1025,
              "pressure_in": 30.27,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 96,
              "cloud": 77,
              "feelslike_c": -14,
              "feelslike_f": 6.9,
              "windchill_c": -14,
              "windchill_f": 6.9,
              "heatindex_c": -9.3,
              "heatindex_f": 15.2,
              "dewpoint_c": -9.8,
              "dewpoint_f": 14.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 11.3,
              "gust_kph": 18.1,
              "uv": 1
            },
            {
              "time_epoch": 1701633600,
              "time": "2023-12-03 21:00",
              "temp_c": -10.6,
              "temp_f": 12.9,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 5.1,
              "wind_kph": 8.3,
              "wind_degree": 219,
              "wind_dir": "SW",
              "pressure_mb": 1026,
              "pressure_in": 30.29,
              "precip_mm": 0.01,
              "precip_in": 0,
              "humidity": 97,
              "cloud": 94,
              "feelslike_c": -15.3,
              "feelslike_f": 4.4,
              "windchill_c": -15.3,
              "windchill_f": 4.4,
              "heatindex_c": -10.6,
              "heatindex_f": 12.9,
              "dewpoint_c": -11,
              "dewpoint_f": 12.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 60,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 10.8,
              "gust_kph": 17.4,
              "uv": 1
            },
            {
              "time_epoch": 1701637200,
              "time": "2023-12-03 22:00",
              "temp_c": -10.3,
              "temp_f": 13.5,
              "is_day": 0,
              "condition": {
                "text": "Light snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/326.png",
                "code": 1213
              },
              "wind_mph": 4.9,
              "wind_kph": 7.9,
              "wind_degree": 225,
              "wind_dir": "SW",
              "pressure_mb": 1026,
              "pressure_in": 30.3,
              "precip_mm": 0.05,
              "precip_in": 0,
              "humidity": 97,
              "cloud": 100,
              "feelslike_c": -14.8,
              "feelslike_f": 5.5,
              "windchill_c": -14.8,
              "windchill_f": 5.5,
              "heatindex_c": -10.3,
              "heatindex_f": 13.5,
              "dewpoint_c": -10.6,
              "dewpoint_f": 12.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 61,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.3,
              "gust_kph": 16.6,
              "uv": 1
            },
            {
              "time_epoch": 1701640800,
              "time": "2023-12-03 23:00",
              "temp_c": -9.1,
              "temp_f": 15.6,
              "is_day": 0,
              "condition": {
                "text": "Light snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/326.png",
                "code": 1213
              },
              "wind_mph": 4.9,
              "wind_kph": 7.9,
              "wind_degree": 225,
              "wind_dir": "SW",
              "pressure_mb": 1026,
              "pressure_in": 30.3,
              "precip_mm": 0.06,
              "precip_in": 0,
              "humidity": 96,
              "cloud": 100,
              "feelslike_c": -13.4,
              "feelslike_f": 7.8,
              "windchill_c": -13.4,
              "windchill_f": 7.8,
              "heatindex_c": -9.1,
              "heatindex_f": 15.6,
              "dewpoint_c": -9.6,
              "dewpoint_f": 14.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 61,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.2,
              "gust_kph": 16.4,
              "uv": 1
            }
          ]
        },
        {
          "date": "2023-12-04",
          "date_epoch": 1701648000,
          "day": {
            "maxtemp_c": -3.1,
            "maxtemp_f": 26.5,
            "mintemp_c": -12.6,
            "mintemp_f": 9.3,
            "avgtemp_c": -7.8,
            "avgtemp_f": 17.9,
            "maxwind_mph": 6.7,
            "maxwind_kph": 10.8,
            "totalprecip_mm": 0.05,
            "totalprecip_in": 0,
            "totalsnow_cm": 0.02,
            "avgvis_km": 6.8,
            "avgvis_miles": 4,
            "avghumidity": 93,
            "daily_will_it_rain": 0,
            "daily_chance_of_rain": 0,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 6,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "uv": 1
          },
          "astro": {
            "sunrise": "07:27 AM",
            "sunset": "03:44 PM",
            "moonrise": "10:42 PM",
            "moonset": "12:29 PM",
            "moon_phase": "Waning Gibbous",
            "moon_illumination": 62,
            "is_moon_up": 1,
            "is_sun_up": 0
          },
          "hour": [
            {
              "time_epoch": 1701644400,
              "time": "2023-12-04 00:00",
              "temp_c": -9.4,
              "temp_f": 15,
              "is_day": 0,
              "condition": {
                "text": "Light snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/326.png",
                "code": 1213
              },
              "wind_mph": 4.9,
              "wind_kph": 7.9,
              "wind_degree": 213,
              "wind_dir": "SSW",
              "pressure_mb": 1026,
              "pressure_in": 30.3,
              "precip_mm": 0.03,
              "precip_in": 0,
              "humidity": 97,
              "cloud": 93,
              "feelslike_c": -13.8,
              "feelslike_f": 7.2,
              "windchill_c": -13.8,
              "windchill_f": 7.2,
              "heatindex_c": -9.4,
              "heatindex_f": 15,
              "dewpoint_c": -9.8,
              "dewpoint_f": 14.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 75,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.3,
              "gust_kph": 16.6,
              "uv": 1
            },
            {
              "time_epoch": 1701648000,
              "time": "2023-12-04 01:00",
              "temp_c": -10.1,
              "temp_f": 13.9,
              "is_day": 0,
              "condition": {
                "text": "Freezing fog",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/260.png",
                "code": 1147
              },
              "wind_mph": 4.9,
              "wind_kph": 7.9,
              "wind_degree": 210,
              "wind_dir": "SSW",
              "pressure_mb": 1026,
              "pressure_in": 30.3,
              "precip_mm": 0.01,
              "precip_in": 0,
              "humidity": 97,
              "cloud": 77,
              "feelslike_c": -14.6,
              "feelslike_f": 5.8,
              "windchill_c": -14.6,
              "windchill_f": 5.8,
              "heatindex_c": -10.1,
              "heatindex_f": 13.9,
              "dewpoint_c": -10.4,
              "dewpoint_f": 13.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 70,
              "vis_km": 0,
              "vis_miles": 0,
              "gust_mph": 10.3,
              "gust_kph": 16.6,
              "uv": 1
            },
            {
              "time_epoch": 1701651600,
              "time": "2023-12-04 02:00",
              "temp_c": -10.4,
              "temp_f": 13.4,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 5.1,
              "wind_kph": 8.3,
              "wind_degree": 209,
              "wind_dir": "SSW",
              "pressure_mb": 1026,
              "pressure_in": 30.31,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 97,
              "cloud": 67,
              "feelslike_c": -15,
              "feelslike_f": 5,
              "windchill_c": -15,
              "windchill_f": 5,
              "heatindex_c": -10.4,
              "heatindex_f": 13.4,
              "dewpoint_c": -10.8,
              "dewpoint_f": 12.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 10.8,
              "gust_kph": 17.4,
              "uv": 1
            },
            {
              "time_epoch": 1701655200,
              "time": "2023-12-04 03:00",
              "temp_c": -11.6,
              "temp_f": 11.1,
              "is_day": 0,
              "condition": {
                "text": "Freezing fog",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/260.png",
                "code": 1147
              },
              "wind_mph": 4.5,
              "wind_kph": 7.2,
              "wind_degree": 205,
              "wind_dir": "SSW",
              "pressure_mb": 1026,
              "pressure_in": 30.31,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 97,
              "cloud": 52,
              "feelslike_c": -16,
              "feelslike_f": 3.2,
              "windchill_c": -16,
              "windchill_f": 3.2,
              "heatindex_c": -11.6,
              "heatindex_f": 11.1,
              "dewpoint_c": -12,
              "dewpoint_f": 10.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 0,
              "vis_miles": 0,
              "gust_mph": 9.4,
              "gust_kph": 15.1,
              "uv": 1
            },
            {
              "time_epoch": 1701658800,
              "time": "2023-12-04 04:00",
              "temp_c": -12.3,
              "temp_f": 9.8,
              "is_day": 0,
              "condition": {
                "text": "Freezing fog",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/260.png",
                "code": 1147
              },
              "wind_mph": 4.3,
              "wind_kph": 6.8,
              "wind_degree": 206,
              "wind_dir": "SSW",
              "pressure_mb": 1027,
              "pressure_in": 30.32,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 97,
              "cloud": 46,
              "feelslike_c": -16.6,
              "feelslike_f": 2.1,
              "windchill_c": -16.6,
              "windchill_f": 2.1,
              "heatindex_c": -12.3,
              "heatindex_f": 9.8,
              "dewpoint_c": -12.6,
              "dewpoint_f": 9.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 0,
              "vis_miles": 0,
              "gust_mph": 8.9,
              "gust_kph": 14.4,
              "uv": 1
            },
            {
              "time_epoch": 1701662400,
              "time": "2023-12-04 05:00",
              "temp_c": -12.6,
              "temp_f": 9.4,
              "is_day": 0,
              "condition": {
                "text": "Freezing fog",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/260.png",
                "code": 1147
              },
              "wind_mph": 4.5,
              "wind_kph": 7.2,
              "wind_degree": 192,
              "wind_dir": "SSW",
              "pressure_mb": 1027,
              "pressure_in": 30.31,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 98,
              "cloud": 23,
              "feelslike_c": -17.1,
              "feelslike_f": 1.2,
              "windchill_c": -17.1,
              "windchill_f": 1.2,
              "heatindex_c": -12.6,
              "heatindex_f": 9.4,
              "dewpoint_c": -12.9,
              "dewpoint_f": 8.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 0,
              "vis_miles": 0,
              "gust_mph": 9.4,
              "gust_kph": 15.1,
              "uv": 1
            },
            {
              "time_epoch": 1701666000,
              "time": "2023-12-04 06:00",
              "temp_c": -12.5,
              "temp_f": 9.5,
              "is_day": 0,
              "condition": {
                "text": "Freezing fog",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/260.png",
                "code": 1147
              },
              "wind_mph": 4.9,
              "wind_kph": 7.9,
              "wind_degree": 198,
              "wind_dir": "SSW",
              "pressure_mb": 1026,
              "pressure_in": 30.31,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 97,
              "cloud": 11,
              "feelslike_c": -17.4,
              "feelslike_f": 0.7,
              "windchill_c": -17.4,
              "windchill_f": 0.7,
              "heatindex_c": -12.5,
              "heatindex_f": 9.5,
              "dewpoint_c": -12.8,
              "dewpoint_f": 8.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 0,
              "vis_miles": 0,
              "gust_mph": 10.3,
              "gust_kph": 16.6,
              "uv": 1
            },
            {
              "time_epoch": 1701669600,
              "time": "2023-12-04 07:00",
              "temp_c": -12.6,
              "temp_f": 9.3,
              "is_day": 0,
              "condition": {
                "text": "Freezing fog",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/260.png",
                "code": 1147
              },
              "wind_mph": 4.5,
              "wind_kph": 7.2,
              "wind_degree": 178,
              "wind_dir": "S",
              "pressure_mb": 1026,
              "pressure_in": 30.31,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 97,
              "cloud": 8,
              "feelslike_c": -17.2,
              "feelslike_f": 1.1,
              "windchill_c": -17.2,
              "windchill_f": 1.1,
              "heatindex_c": -12.6,
              "heatindex_f": 9.3,
              "dewpoint_c": -13,
              "dewpoint_f": 8.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 0,
              "vis_miles": 0,
              "gust_mph": 9.4,
              "gust_kph": 15.1,
              "uv": 1
            },
            {
              "time_epoch": 1701673200,
              "time": "2023-12-04 08:00",
              "temp_c": -12.4,
              "temp_f": 9.7,
              "is_day": 1,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/143.png",
                "code": 1030
              },
              "wind_mph": 4.9,
              "wind_kph": 7.9,
              "wind_degree": 171,
              "wind_dir": "S",
              "pressure_mb": 1026,
              "pressure_in": 30.31,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 97,
              "cloud": 6,
              "feelslike_c": -17.3,
              "feelslike_f": 0.9,
              "windchill_c": -17.3,
              "windchill_f": 0.9,
              "heatindex_c": -12.4,
              "heatindex_f": 9.7,
              "dewpoint_c": -12.8,
              "dewpoint_f": 8.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 10.3,
              "gust_kph": 16.6,
              "uv": 1
            },
            {
              "time_epoch": 1701676800,
              "time": "2023-12-04 09:00",
              "temp_c": -9,
              "temp_f": 15.8,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 5.4,
              "wind_kph": 8.6,
              "wind_degree": 175,
              "wind_dir": "S",
              "pressure_mb": 1026,
              "pressure_in": 30.3,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 92,
              "cloud": 33,
              "feelslike_c": -13.6,
              "feelslike_f": 7.6,
              "windchill_c": -13.6,
              "windchill_f": 7.6,
              "heatindex_c": -9,
              "heatindex_f": 15.8,
              "dewpoint_c": -10,
              "dewpoint_f": 14,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.9,
              "gust_kph": 17.5,
              "uv": 2
            },
            {
              "time_epoch": 1701680400,
              "time": "2023-12-04 10:00",
              "temp_c": -6.6,
              "temp_f": 20.2,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 6.5,
              "wind_kph": 10.4,
              "wind_degree": 176,
              "wind_dir": "S",
              "pressure_mb": 1026,
              "pressure_in": 30.28,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 89,
              "cloud": 5,
              "feelslike_c": -11.3,
              "feelslike_f": 11.7,
              "windchill_c": -11.3,
              "windchill_f": 11.7,
              "heatindex_c": -6.6,
              "heatindex_f": 20.2,
              "dewpoint_c": -8.1,
              "dewpoint_f": 17.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10,
              "gust_kph": 16.1,
              "uv": 2
            },
            {
              "time_epoch": 1701684000,
              "time": "2023-12-04 11:00",
              "temp_c": -4.8,
              "temp_f": 23.3,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 6.7,
              "wind_kph": 10.8,
              "wind_degree": 167,
              "wind_dir": "SSE",
              "pressure_mb": 1025,
              "pressure_in": 30.26,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 86,
              "cloud": 4,
              "feelslike_c": -9.3,
              "feelslike_f": 15.2,
              "windchill_c": -9.3,
              "windchill_f": 15.2,
              "heatindex_c": -4.8,
              "heatindex_f": 23.3,
              "dewpoint_c": -6.8,
              "dewpoint_f": 19.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 9.2,
              "gust_kph": 14.8,
              "uv": 2
            },
            {
              "time_epoch": 1701687600,
              "time": "2023-12-04 12:00",
              "temp_c": -3.6,
              "temp_f": 25.4,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 6.5,
              "wind_kph": 10.4,
              "wind_degree": 157,
              "wind_dir": "SSE",
              "pressure_mb": 1024,
              "pressure_in": 30.23,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 84,
              "cloud": 5,
              "feelslike_c": -7.8,
              "feelslike_f": 18,
              "windchill_c": -7.8,
              "windchill_f": 18,
              "heatindex_c": -3.7,
              "heatindex_f": 25.4,
              "dewpoint_c": -5.9,
              "dewpoint_f": 21.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 8.7,
              "gust_kph": 13.9,
              "uv": 2
            },
            {
              "time_epoch": 1701691200,
              "time": "2023-12-04 13:00",
              "temp_c": -3.1,
              "temp_f": 26.5,
              "is_day": 1,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                "code": 1009
              },
              "wind_mph": 6.5,
              "wind_kph": 10.4,
              "wind_degree": 145,
              "wind_dir": "SE",
              "pressure_mb": 1023,
              "pressure_in": 30.21,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 84,
              "cloud": 100,
              "feelslike_c": -7.1,
              "feelslike_f": 19.2,
              "windchill_c": -7.1,
              "windchill_f": 19.2,
              "heatindex_c": -3.1,
              "heatindex_f": 26.5,
              "dewpoint_c": -5.4,
              "dewpoint_f": 22.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 8.9,
              "gust_kph": 14.4,
              "uv": 1
            },
            {
              "time_epoch": 1701694800,
              "time": "2023-12-04 14:00",
              "temp_c": -3.1,
              "temp_f": 26.4,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 5.6,
              "wind_kph": 9,
              "wind_degree": 138,
              "wind_dir": "SE",
              "pressure_mb": 1022,
              "pressure_in": 30.19,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 88,
              "cloud": 6,
              "feelslike_c": -6.7,
              "feelslike_f": 19.9,
              "windchill_c": -6.7,
              "windchill_f": 19.9,
              "heatindex_c": -3.1,
              "heatindex_f": 26.4,
              "dewpoint_c": -4.7,
              "dewpoint_f": 23.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 8.5,
              "gust_kph": 13.6,
              "uv": 2
            },
            {
              "time_epoch": 1701698400,
              "time": "2023-12-04 15:00",
              "temp_c": -4.5,
              "temp_f": 24,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 5.8,
              "wind_kph": 9.4,
              "wind_degree": 125,
              "wind_dir": "SE",
              "pressure_mb": 1022,
              "pressure_in": 30.17,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 91,
              "cloud": 32,
              "feelslike_c": -8.4,
              "feelslike_f": 16.8,
              "windchill_c": -8.4,
              "windchill_f": 16.8,
              "heatindex_c": -4.5,
              "heatindex_f": 24,
              "dewpoint_c": -5.7,
              "dewpoint_f": 21.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11.2,
              "gust_kph": 18,
              "uv": 2
            },
            {
              "time_epoch": 1701702000,
              "time": "2023-12-04 16:00",
              "temp_c": -7.2,
              "temp_f": 19,
              "is_day": 0,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
              },
              "wind_mph": 6,
              "wind_kph": 9.7,
              "wind_degree": 114,
              "wind_dir": "ESE",
              "pressure_mb": 1022,
              "pressure_in": 30.17,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 94,
              "cloud": 84,
              "feelslike_c": -11.8,
              "feelslike_f": 10.7,
              "windchill_c": -11.8,
              "windchill_f": 10.7,
              "heatindex_c": -7.2,
              "heatindex_f": 19,
              "dewpoint_c": -8,
              "dewpoint_f": 17.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.7,
              "gust_kph": 20.4,
              "uv": 1
            },
            {
              "time_epoch": 1701705600,
              "time": "2023-12-04 17:00",
              "temp_c": -6.3,
              "temp_f": 20.6,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 6.5,
              "wind_kph": 10.4,
              "wind_degree": 118,
              "wind_dir": "ESE",
              "pressure_mb": 1021,
              "pressure_in": 30.15,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 92,
              "cloud": 22,
              "feelslike_c": -11,
              "feelslike_f": 12.1,
              "windchill_c": -11,
              "windchill_f": 12.1,
              "heatindex_c": -6.3,
              "heatindex_f": 20.6,
              "dewpoint_c": -7.4,
              "dewpoint_f": 18.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.6,
              "gust_kph": 21.9,
              "uv": 1
            },
            {
              "time_epoch": 1701709200,
              "time": "2023-12-04 18:00",
              "temp_c": -6,
              "temp_f": 21.2,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 6.7,
              "wind_kph": 10.8,
              "wind_degree": 126,
              "wind_dir": "SE",
              "pressure_mb": 1021,
              "pressure_in": 30.14,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 91,
              "cloud": 96,
              "feelslike_c": -10.7,
              "feelslike_f": 12.7,
              "windchill_c": -10.7,
              "windchill_f": 12.7,
              "heatindex_c": -6,
              "heatindex_f": 21.2,
              "dewpoint_c": -7.2,
              "dewpoint_f": 19.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.1,
              "gust_kph": 22.7,
              "uv": 1
            },
            {
              "time_epoch": 1701712800,
              "time": "2023-12-04 19:00",
              "temp_c": -5.8,
              "temp_f": 21.6,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 6,
              "wind_kph": 9.7,
              "wind_degree": 130,
              "wind_dir": "SE",
              "pressure_mb": 1020,
              "pressure_in": 30.13,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 92,
              "cloud": 100,
              "feelslike_c": -10.1,
              "feelslike_f": 13.8,
              "windchill_c": -10.1,
              "windchill_f": 13.8,
              "heatindex_c": -5.8,
              "heatindex_f": 21.6,
              "dewpoint_c": -6.9,
              "dewpoint_f": 19.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.7,
              "gust_kph": 20.4,
              "uv": 1
            },
            {
              "time_epoch": 1701716400,
              "time": "2023-12-04 20:00",
              "temp_c": -5.9,
              "temp_f": 21.4,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 5.4,
              "wind_kph": 8.6,
              "wind_degree": 132,
              "wind_dir": "SE",
              "pressure_mb": 1020,
              "pressure_in": 30.11,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 92,
              "cloud": 100,
              "feelslike_c": -9.9,
              "feelslike_f": 14.2,
              "windchill_c": -9.9,
              "windchill_f": 14.2,
              "heatindex_c": -5.9,
              "heatindex_f": 21.4,
              "dewpoint_c": -7,
              "dewpoint_f": 19.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11.3,
              "gust_kph": 18.1,
              "uv": 1
            },
            {
              "time_epoch": 1701720000,
              "time": "2023-12-04 21:00",
              "temp_c": -5.9,
              "temp_f": 21.4,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 4.7,
              "wind_kph": 7.6,
              "wind_degree": 139,
              "wind_dir": "SE",
              "pressure_mb": 1019,
              "pressure_in": 30.1,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 92,
              "cloud": 100,
              "feelslike_c": -9.5,
              "feelslike_f": 15,
              "windchill_c": -9.5,
              "windchill_f": 15,
              "heatindex_c": -5.9,
              "heatindex_f": 21.4,
              "dewpoint_c": -6.9,
              "dewpoint_f": 19.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 9.9,
              "gust_kph": 15.9,
              "uv": 1
            },
            {
              "time_epoch": 1701723600,
              "time": "2023-12-04 22:00",
              "temp_c": -6.3,
              "temp_f": 20.7,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 3.6,
              "wind_kph": 5.8,
              "wind_degree": 142,
              "wind_dir": "SE",
              "pressure_mb": 1019,
              "pressure_in": 30.09,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 93,
              "cloud": 88,
              "feelslike_c": -9.1,
              "feelslike_f": 15.6,
              "windchill_c": -9.1,
              "windchill_f": 15.6,
              "heatindex_c": -6.3,
              "heatindex_f": 20.8,
              "dewpoint_c": -7.2,
              "dewpoint_f": 19.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 7.5,
              "gust_kph": 12.1,
              "uv": 1
            },
            {
              "time_epoch": 1701727200,
              "time": "2023-12-04 23:00",
              "temp_c": -6.4,
              "temp_f": 20.5,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 135,
              "wind_dir": "SE",
              "pressure_mb": 1019,
              "pressure_in": 30.08,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 93,
              "cloud": 53,
              "feelslike_c": -9.5,
              "feelslike_f": 15,
              "windchill_c": -9.5,
              "windchill_f": 15,
              "heatindex_c": -6.4,
              "heatindex_f": 20.5,
              "dewpoint_c": -7.3,
              "dewpoint_f": 18.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 8,
              "gust_kph": 12.9,
              "uv": 1
            }
          ]
        }
      ]
    }
  } as unknown as ForecastWeatherResponse
);
